# name: work
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy=1.22.3
  - jupyterlab=3.3.2
  - scipy=1.7.3
  - xarray=0.20.1
  - netcdf4
  - zarr
  - matplotlib=3.5.1
  - cartopy=0.18.0
  - scikit-learn=1.0.2
  - dask=2022.5.0
